services:
  app:
    container_name: ecommerce-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file: .env 
    environment:
      DB_HOST: db 
    networks:
      - ecommerce 
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ecommerce-db
    image: postgres:16.10 
    ports:
      - "8004:5432" 
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - ecommerce 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s 
      retries: 3

networks:
  ecommerce:
    name: ecommerce 
    driver: bridge 

volumes:
  db-data: