name: Build and Test 

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false 
            matrix:
                python-version: ["3.12"]

        steps:
        - uses: actions/checkout@v4 
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3 
          with: 
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies 
          run: | 
            pip install poetry 
            poetry install --no-root
        - name: Load env variables
          env:
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            ALGORITHM: ${{ secrets.ALGORITHM }}
            ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
            REFRESH_TOKEN_EXPIRE_DAYS: ${{ secrets.REFRESH_TOKEN_EXPIRE_DAYS }}
          run: poetry run python -m pytest 

